.TH PASSENGER 1 "May 2024" "0.1.0" "Passenger CLI Manual"
.SH NAME
Passenger \- Portable and customizable password manager.
.SH SYNOPSIS
.B passenger
[command] [*args]
.SH DESCRIPTION
.B Passenger
is a command line password manager designed to be portable and customizable. It allows users to securely store, retrieve, manage, and generate passphrases using their own encode/decode algorithm, created from the open-source EnDeCoder.cs file. Each build of the Passenger client is unique, crafted by the user, ensuring a personalized security algorithm.
.SH COMMANDS
.TP
.BR login " \-l"
Generate a JWT token to use other commands. Requires a passphrase.
.RS
.B passenger login \-l [username] [passphrase]
.RE
.TP
.BR register " \-r"
Register a passphrase to the Passenger client.
.RS
.B passenger register [username] [passphrase]
.RE
.TP
.BR reset " \-R"
Reset the passphrase of the Passenger client using a JWT token and a new passphrase.
.RS
.B passenger reset [jwt] [new]
.RE
.TP
.BR fetchAll " \-a"
List all entries without displaying their passphrases, requires a JWT token.
.RS
.B passenger fetchAll [jwt]
.RE
.TP
.BR query " \-q"
Search for a keyword in all entries, requires a JWT token.
.RS
.B passenger query [jwt] [keyword]
.RE
.TP
.BR fetch " \-f"
Retrieve an entry by its UUID, requires a JWT token.
.RS
.B passenger fetch [jwt] [uuid]
.RE
.TP
.BR create " \-c"
Store an entry with the given json, requires a JWT token.
.RS
.B passenger create [jwt] [json]
.RE
.TP
.BR update " \-u"
Update an entry by its UUID, requires a JWT token and JSON formatted json.
.RS
.B passenger update [jwt] [uuid] [json]
.RE
.TP
.BR delete " \-d"
Delete an entry by its UUID, requires a JWT token.
.RS
.B passenger delete [jwt] [uuid]
.RE
.TP
.BR version " \-v" " \-\-version"
Show the version of the Passenger software.
.RS
.B passenger version 
.RE
.TP
.BR generate " \-g"
Generate a passphrase with the given length, requires a JWT token.
.RS
.B passenger generate [jwt] [length]
.RE
.TP
.BR manipulate " \-m"
Manipulate a passphrase by changing characters looking similar to others.
.RS
.B passenger manipulate [jwt] [passphrase]
.RE
.TP
.BR help " \-h" " \-\-help"
Show this help message and exit.
.RS
.B passenger help
.RE
.TP
.BR man " \-M"
Show the manual page.
.RS
.B passenger man
.RE
.SH AUTHOR
Written by Elagoht.
.SH "SEE ALSO"
.BR jq (1)
